# Generated by Django 4.2.3 on 2023-08-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_no',
            new_name='customer_name',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(blank=True, default=872302, editable=False, max_length=7, null=True),
        ),
    ]
