# Generated by Django 4.2.3 on 2023-08-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_invoice_invoice_no_alter_invoicedetail_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(blank=True, default=261687, editable=False, max_length=7, null=True),
        ),
    ]
